apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-server
webhooks:
- name: webhook-server.default.svc
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1EVXhNVEUyTkRJd01sb1hEVEk1TURVd09ERTJOREl3TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3crClZFR29YeWFxVGFncWJiZHJYN3ZMTFQ4ZmMwbFQ4a01hUXNlZldmUWxrVHVkZm91czhYYzUxdVh4eU1vbm5aSUQKZXpWK3FiWmlXL0JVdy9mSUU2Q3k5L296S3FBcHRvT2R3Y0MrYnNpL3V0clovUDFuVFU1OXRtUTN2TTh2SFEzZwpmd0FUYlVMYzRKM2pWVXh2MlV2dVBpcWZQNVMvRXFucm9QMVpNenRWT2RWWFBaN3U5OGREWlRnTk9xMTloN1BTCjhhVlVJR1FyMUd0anpnV3FhalpINmgvV1FjQ0ZLWVY2M2Q1OCt2S1dOdXNxV1REMkc3ZllBc0lHMHQ2YWlPRTIKZTE2MXlOWHV4cTlUc0x5cFNZT1lkM0I3NHhXTm1FRVhwWjQ2RkVvb3BhY3RLdlduV0lzeDhoeEdzMk9DZjFnQgo5bzVIalFudVp6WnEwNHF0NXVNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKWHRGQ2JrSHlxTUlWUDFwSjlEZ2N6ZlZxbTUKTHpzSFphazBNalhCNGZnSFNIOGhBMUl3RVFYYjE2M1hnVHkzM0tQMUJJSzBUTHliTUZpN2MvQ25Ob3lZSDY1cwp6Z2lxRHFKNDExeXBCNGt3Ykk0VmE1ZmZyZ1JLRFNjTitoZDl6d1V1NmVsbThpTUJONXRrZUhOMlNkWGFiQi9MCnBvKzdiTlZsZXkwY0lHRDZkdFBnQngzdndXc1dxa01UWTkvaVNyeGhaa2JpSmk3dGYzQnVwaDQ2ZmFmaG9vZDgKSHR6MnE3WkhZYmtFdmxRMjRPeVNyb3I5U0J6U2IyVTdvOERmU3B6M0NIN3NDYWRIL1R3ekE5dEdHVnlzYUdPVgpFeDE1V0J4ZzdFalQxZEU0azNqc3phSzJlUnlUdUh5M0RhSVNvMmZsMlU4blZHV2s0UEFvWTlhMTZ4az0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-server
      namespace: default
      path: /mutate
  timeoutSeconds: 30
  failurePolicy: Ignore
  namespaceSelector:
    matchExpressions:
    - key: role
      operator: NotIn 
      values: ["system"]
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE", "UPDATE"] 
    resources: ["pods"]
    scope: Namespaced
