apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-server
  namespace: default
data:
  rules.json: |
    {
      "defaultselector": "env=banana",
      "rules": {
      "development":  "env=development",
      "production":   "env=production",
      "infra":        "env=infra"
      }
    }
